### ISSUE TITLE
Align language in section titles

### ISSUE THREAD

**Issue by mnot** [w3ctag/ethical-web-principles#121]
The language in the principle section titles is inconsistent. 

Many are positioned as statements of fact ("The Web is...", "The Web does not..."), but one is stated as a requirement ("The Web must...") and one is stated as a capability ("People can....").

Looking at the document with fresh eyes, I'd strongly recommend that they be normalised to be stated as requirements ("The Web must..."). Defining principles as statements of fact is confusing -- readers will misinterpret them as, well, statements of fact, and in some cases they are obviously NOT factual on the current Web.

**Comment by rhiaro** [comment]
Thanks Mark. A few months ago we went back and forth on this in #75 and landed on making them consistent as aspirational present-tense statements. It looks like the stray "The web must" slipped through the net in #105 which I can correct so it matches the others. If I recall our discussions correctly, we steered away from normative spec language in this case, as it's not a spec.

**Comment by mnot** [comment]
I'd urge you to reconsider that -- principles _are_ normative statements, by definition.

**Comment by darobin** [comment]
I agree with @mnot. Either they're aspirational or they're principles, but they can't be principles but informative. There are words we use to describe people who have principles solely for informative purposes, and none of them are very nice.

Aren't these meant to be used in review? If so, they're enforceable, not aspirational.

**Comment by torgo** [comment]
Hi folks - as discussed in this morning's TAG breakout : we have aligned the language of these statements but we have done so based on the discussions we have had in #75 - that these should be guiding principles and therefore not use normative language. These guiding principles are then used to *guide* development of the actionable principles which are used in the context of reviews - such as those in the [Design Principles](https://www.w3.org/TR/design-principles/) and [Privacy Principles](https://www.w3.org/TR/privacy-principles/). We also received community feedback early on that these principles should be written in simple, easy to understand, language rather than as "spec text." What we propose is that we move ahead on the statement track with the principles in this form and then revisit for the next version based on feedback. Let us know if that sounds OK.

**Comment by mnot** [comment]
It doesn't sound OK.

Again, principles _are_ normative -- they are expectations about how things will be (i.e., proscriptive, not descriptive). As stated the document is confused about what it's doing.

This could be fixed by either making the section titles proscriptive, or by changing the title and framing of the document (e.g., "Ethical Web Aspirations").

**Comment by darobin** [comment]
This is leading to one of the same issues that made the "Vision" doc inoperative: either it is something that we intend to govern things we do and if so it needs to be normative and enforceable (unenforced rules do not exist) or it's an informative document describing aspects of the W3C culture, perhaps intended to help bring people into the fold but not to guide the work.

It's fine to write the latter, but if that's the case it should be clearly indicated as such. Right now the doc says "The following document sets out ethical principles that will **drive** the W3C's continuing work in this direction." (Emphasis mine.) There are basically two broad possible outcomes:

- This is informational, presented as documenting the ethics of some influential people in the community. If tomorrow I propose something that goes against this documentation, that is not a worthy ground on which to motivate for instance an FO. I can always claim that the web is plural and we are not bound by ethnographic documentation.
- This is intended to actually drive work, and it must be enforceable, grounds for appeals, etc.

"We have strong principles but they're optional" isn't really the outcome that I would prefer for this document. And regarding "spec text", "must" is the 261st most frequent word in the English language in the AMALGUM corpus (that includes punctuation), which makes it more frequent than "why", "party", or "dog". I think it's manageable?

**Comment by torgo** [comment]
@darobin @mnot do you have specific suggestions for re-wording of the principles themselves that would also satisfy my requirement that the text be concise, easy to understand and easy to engage with?

**Comment by torgo** [comment]
I will note that the [Universal Declaration of Human Rights](https://www.un.org/en/about-us/universal-declaration-of-human-rights) contains many statements of the form "Everyone has the right to freedom of opinion and expression…", not "Member states SHALL ensure that individuals residing therein are able to express themselves in many different modalities, not limited to…" That doesn't stop the UDHR from being influential and *driving* work on Human Rights inside and outside of the UN.

**Comment by darobin** [comment]
Forgive my reference to stuff that is decidedly _not_ written in easy language, but I think it matters and can help resolve the issue at hand. Those RFC2919 keywords don't exist in vacuum and weren't invented for the internet, they correspond to [deontic logic](https://en.wikipedia.org/wiki/Deontic_logic) (providing the link for reference, but as usual Wikipedia is unreadable on anything even vaguely maths related). Deontic logic is the logic of action, it's things that you may, must, or must not do. ("Should" does not figure in it, though more on that below.)

Deontic logic is pretty intuitive and easy to understand (Wikipedia's efforts to the contrary notwithstanding). You use $Pa$ to say that $a$ is permitted (may), and similarly $Ob$ if you must do $b$ and $Fc$ if you must not $c$. Interestingly (for nerds), each operator (may, must, must not) is primitive and can be used to express the other two. Notably, within the scope of the question at hand, may can be expressed in terms of must: $Pa = \neg O(a \lor \neg a)$ (If you may $a$ then neither must $a$ nor must not $a$ — you are neither obligated nor forbidden to $a$).

I'm not explaining a corner of logic for the amusement value it delivers: deontic logic is a core component in governance and institutional design. A typical framework to analyse the grammar of institutions is ADICO, in which the D is for Deontic. (The O is for "Or Else", when that is absent you have a "should".) Rules that are meaningful in a governance context will therefore rely on a deontic — when they don't, they don't exist.

Bringing this together: in the UDHR, "has the right to" is a longer way of saying "may" — you can rewrite every single one of those statements as a may statement. Everyone MAY exercise freedom of opinion is straightforwardly equivalent to people can neither be obligated nor forbidden to hold an opinion. You can parse the entire Declaration in those terms: it's all about rules, not aspirations. (Making the rules apply more often to more people may be an aspiration — but that does _not_ mean that human rights are aspirational, optional, informational.)

Again, this is not to say that we need to mimic the Declaration. But if our goal is to operate at that level and to be credible with international governance groups, we need to write and operate in a way that meshes with their expectations.

**Comment by torgo** [comment]
With all due respect, I don't see how what you've written above is at odds with the way the document is currently written. Each principle starts with a statement about the web. We then go into some detail and every single principle includes at least one statement of the form "we will..." e.g. under "2.2 The web does not cause harm to society" we start with "When we are adding a feature or technology to the web, **we will** work to prevent or mitigate any harm it might cause society or groups, especially to vulnerable people." Doesn't this also satisfy the requirement - since each of these statements could be read as a "shall"? 

I'll note that the [Ethical Principles for Web Machine Learning](https://www.w3.org/TR/webmachinelearning-ethics/), and the UNESCO AI Ethics doc that it references, also seem to have gone in a similar direction - simple to understand principle followed by more specific normative language.

**Comment by darobin** [comment]
You asked why the UDHR said "has the right to" and I explained?

Weakening the language of section headings could be fine given strong, binding language in the descriptions. But taking the no harm section as an example:

- we will work
- we consider
- we will prioritize potential benefits
- we commit to learning about
- we will strive to reflect a respect

That's giving ourselves a pass. Things are bad but in keeping with our principles we considered and we strove!

Yes, the UNESCO AI principles are written using weak, non-binding language. That's not an accident and I would encourage you to read them with an eye towards what that means: they are written to be non-binding because they couldn't make them binding because powerful-enough UNESCO members don't want them binding. When we use similar language, they assumption is going to be that it's the same for us. Is that what we want?

**Comment by mnot** [comment]
@torgo the declaration of human rights is just that - a _declaration_ about the state of the world (in this case, the nature of human rights). 

Fundamentally, this document is about _how we want things to be_ on the web, not describing its properties. 

The suggested remedies are as above -- either change the title and framing of the document so that it's more clearly aspirational, or change the section titles to be stated as actual principles.

**Comment by rhiaro** [comment]
> That's giving ourselves a pass.

I'm in favour of reducing the amount of hedging language in the document, if that is actually what would address the core need here. I'm not convinced the problem/solution lies in the section headings (I don't think present-tense statements about the ideal state are "weak").

**Comment by darobin** [comment]
My point is that someone has to be on the hook for this and that has to go _somewhere_. If the headings are present-tense statements about an ideal state, it also sounds like nobody's fault when that state isn't realised. The description text can indeed probably address that, but with description text then being all about aiming and thinking and considering, when we fail no one's accountable. 

This de-hedges as much as I could figure out without more extensive rewriting: #123.

**Comment by mnot** [comment]
@darobin it's sounding like your issue is different from what I've raised here. My primary concern is that a reader is going to be confused by the conflicting positioning of this document as "principles" and the aspirational nature of the text (as reflected primarily in the section titles, but possibly elsewhere too). As I mention above, the fixes for that are fairly straightforward, and I don't have strong feelings about which way it should go -- it just needs to be aligned.

**Comment by torgo** [comment]
We decided to make [this change](https://github.com/w3ctag/ethical-web-principles/pull/130) to align the titles. We recognise that this doesn't address all the concerns raised in this issue, but on balance we think having the more simple language has value. Hence we're going to close this.
