### ISSUE TITLE
Say something about resisting interpersonal abuse

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/ethical-web-principles#44]
The principles currently address governments surveilling their populations, but I don't see anything that covers employers, intimate partners, parents who oppose their child's identity or health care, etc. This is relevant to https://github.com/w3ctag/design-reviews/issues/606, but I think broader than just the case of managed devices.

Web API design won't always be able to improve the situation, but we should watch for places it can.

**Comment by torgo** [comment]
We discussed today about adding some text to EWP to reflect this. @hadleybeeman will work on writing something.

**Comment by OR13** [comment]
This is a really important issue. 

[facebook-reportedly-fired-52-workers-who-were-caught-spying-on-women...](https://nypost.com/2021/07/13/facebook-reportedly-fired-52-workers-who-were-caught-spying-on-women/).

[nsa-staff-used-spy-tools-on-spouses-ex-lovers...](https://www.reuters.com/article/us-usa-surveillance-watchdog/nsa-staff-used-spy-tools-on-spouses-ex-lovers-watchdog-idUSBRE98Q14G20130927)

**Comment by tobie** [comment]
Yes. This is a particularly important issue because it falls outside of the boundaries of common security practices which generally consider additional mitigation approaches as moot on compromised machines. A lot of common behavior between spouses (or other related intrapersonal relationships) create situations that fall under this category: shared computers, shared browsers, shared passwords, etc.

This narrow minded perspective ignores two fundamental aspects.

One, how prevalent this issue is. When I first started raising this issue at Facebook about a decade ago, searching for how to access your husband/wife’s Facebook account was returning over 50 million results on Google Search. 

Two, that in a significant number of those cases, the attacker is everything but sophisticated and that additions deterrents  can be highly effective at reducing harm.

**Comment by nshadowen314** [comment]
If I can jump in, this addition is critical to any ethical framework of web principles. Safety for individuals, families, and society is a value that can sometimes seem at odds with traditional criteria of privacy/security, but is nonetheless a real and felt problem at some point in the lives of a majority of global web users. It is worth encouraging threat modeling to understand and build for these tradeoffs.

I would ask the group to include globally recognized crimes against children online, such as online grooming, exploitation, harassment, and abuse, which can occur at the hands of known family members or strangers. Because of the properties of online technologies, when these material or interactions occur online, they may exist in perpetuity, which can then cause repeat trauma for survivors and their loved ones.

Taking this into account, including a principle about safety and a web that counters abuse by design, will help to incorporate lessons from this very real phenomenon that threatens the benefits of the global web to users equally.

**Comment by hadleybeeman** [comment]
Discussed in today's W3CTAG breakout. We looked at how this issue relates to our design review for the proposal of a [Managed Device Web API](https://github.com/w3ctag/design-reviews/issues/606).

**Comment by torgo** [comment]
We're going to try to work on this one at the f2f in 2 weeks.

**Comment by torgo** [comment]
So we haven't managed to address this yet though we still think it's important enough that we should do something before we progress the doc along Statement track.

**Comment by rhiaro** [comment]
Merged #108 to address this, as succinctly as possible
