### ISSUE TITLE
"open and decentralised"

### ISSUE THREAD

**Issue by triblondon** [w3ctag/ethical-web-principles#6]
The web is often referred to an 'open and decentralised'.  I don't see any definitions of references to those terms in this document.  Should there be?

"Open" I've often had problems with.  It's frequently touted, I believe because it's safe to do so without actually signing up to anything tangible.  'Open', is, essentially, a subjective judgement.  The TAG could try to make it more objective, but I'm actually not sure what the definition would be.  Do we mean 'open source' (and then presumably only in relation to browser-executed code, but not browsers themselves? And what about webassembly?).  I assume we don't mean 'open access' since much of the web isn't.

"Decentralised" is much easier to define, but less frequently lauded.  It should receive more attention. There exist perverse incentives on companies that have developed (though their own innovation and quality products) an outsize influence over the web.  They now stand to benefit substantially if the web can become more and more within their ecosystem.

The joke that pops up every time GitHub goes down is worth some thought: "Hey, at least git is decentralised, huh!"

**Comment by torgo** [comment]
Maybe this needs to be some additional sentetnce or sentences under "enhance individuals' control and power" that explain why decentralization is a key enabler there?

**Comment by hadleybeeman** [comment]
I agree that.. I think decentralisation is valuable not for its own sake, but for the amount to which it empowers individuals over large organisations with a lot of resources. If we have a proposed new feature for the web that means that only a team of 500 developers could build a website, that disadvantages the individual web developer who used to be able to build a website by themselves.

So I think this fits well with "enhance individuals' control and power"... And I do think it's worth making clear. Somehow the ideal fell out of our last round of drafting, so I'm glad you brought it up, @triblondon.

**Comment by jyasskin** [comment]
Another aspect of this might be that it matters which aspects of the web are being decentralized. Decentralizing the most-powerful entities on the web (probably the search engines and social networks today) is probably beneficial. Decentralizing the next tier removes a possible [countervailing power](https://www.vox.com/policy-and-politics/2019/5/17/18626801/2020-democrats-sanders-warren-buttigieg-power-socialism) to that top tier, and so might lead to less individual power.

**Comment by masinter** [comment]
decentralization helps with reducing single-points-of-failure, where you include organizational failure in the considerations (e.g., failure of trust or maintenance of service or data.)  The big "monopoly" services are dangerous because they are too big to fail or even be restrained. 
The only countervailing force outside of (ineffective) regulation is the focus on independent interoperable implementations, so that no single or small set of implementations prevail.

**Comment by hadleybeeman** [comment]
[Pull request](https://github.com/w3ctag/ethical-web-principles/pull/15) with suggested edits. Thanks for everyone's help with this!

**Comment by masinter** [comment]
https://open-stand.org/  has a definition of "open" and linked to benefits.
And W3C seems to be listed as an organization supporting its principles.

**Comment by dbaron** [comment]
So I think I support what you're asking for about decentralization, but I'm also a little hesitant to use the term decentralization in this context because I think some people tend to use it in a different way.  For example, I see some people complain about the centralization of DNS, whereas I think DNS, while centralized, is one of the things that allows anybody who wishes to do so to register a hostname, mint URIs, and play a part on the Web.  The approaches I've seen to "decentralize" DNS seem like they would make the web less open and accessible to users and other participants in the system.

That said, I don't have strong suggestions about alternative wording.  I think some of what's relevant here is that we want end users to be able to have some combination of *power* to do what the more powerful players can do, and effective *choice* between options if they don't want to build their own.

**Comment by torgo** [comment]
@dbaron Hadley and I are discussing and we still feel the wording is OK. It talks about "favoring" distributed architectures vs. central points of control but doesn't call for replacement of lower-level architectural elements (e.g. DNS). Would you be OK with keeping the wording or have you had any thoughts about a more palatable alternative?

**Comment by twifkak** [comment]
@torgo I don't see the wording you're referring to. Are you talking about the `Tokyo-edits` branch? I see this:

> We will favour a decentralized web architecture that minimises single points of failure and single points of control.

Is the plan to merge that into `gh-pages`?

**Comment by hadleybeeman** [comment]
Addressed in [pull request](https://github.com/w3ctag/ethical-web-principles/pull/15) and merged at [TAG Cupertino face-to-face](https://github.com/w3ctag/meetings/blob/gh-pages/2019/12-cupertino/README.md).
