### ISSUE TITLE
Offer a framework to handle conflicts between principles

### ISSUE THREAD

**Issue by tobie** [w3ctag/ethical-web-principles#63]
What happens when improving privacy increases your environment footprint or makes controlling the spread of disinformation more difficult?

Which principle should you favor and why?

Is there a priority of principles likes there is a priority of constituencies?

Can you make tradeoff and if so, based on what?

Can the TAG help and if so how do you get their help?

Building on #62, it would be great to have a framework to navigate conflicts between principles, or at least a set of suggestions to do so.

**Comment by lknik** [comment]
Good questions. I'm wondering either about the priority or a possibility to balance the principles. There seem to be no easy solution here, other than mention the need of balancing. But how to balance, then? Who should do this? Won't this end in making the principles more legalistic (balancing is a typical legal approach)?

Also, good catch about the hypothesis of the potential privacy/encryption/etc environmental toll.

**Comment by rxgrant** [comment]
Questions I'd add:

* Are we going to focus on the math, when we can?
* (when someone has to do the math) Who has the burden of proof for claims that a WG has failed to consider the collective good?

**Comment by mnot** [comment]
I share @lknik's concern here - this isn't algorithmic, someone will need to perform the balancing process, and it's likely to be inherently legalistic. This document is an expression of principles; if legal reasoning is any guide, how to balance them will need to be explored and documented through much discussion and experience, not merely written down ahead of time. Or, as per Coffin:

> Perhaps the biggest problem with the balancing metaphor is that it suggests a mechanistic, quantitative, and utilitarian comparison of the weight or value of two claims according to one scale which is equally appropriate to both. This is, however, a condition rarely found in the matrix of conflicting values that is the stuff of most cases...[^1]

That said, he does give a pretty good indication of the properties to look for in such a process:

> After the issue and the level of generality have been carefully identified and justified, adequate facts fairly set forth, the opposing interests fully and credibly canvassed, the appropriateness or fit of a rule sensitively considered, and a reasonable dialogue between majority and minority conducted, there comes the moment of choice, the "moment of truth." Here is the fulcrum where judges' subjective values will inevitably come to bear and affect the balance. But in the process those values have been both contained and exposed. Although all this does not add up to perfect objectivity, it gives us as close an approximation as we are likely to realize in this complex, moving, and fallible human enterprise.[^2]

Of course, that's written with the legal system in mind, but I think there's a certain amount of applicability here.

The most immediate risk I can see is that the principles we document will be necessarily incomplete, and it's difficult to balance something well-defined against something that we forgot -- or something that we assumed would be accounted for. Considering this document only talks about principles, not rights or interests of various parties, that could get pretty sticky.

It's also probably necessary to acknowledge that efforts at balancing are 'at heart arguments, offered to legitimise the exercise of political authority in particular settings.'[^3] Habermas would go further and say that they are weighted 'either arbitrarily or unreflectively according to customary standards and hierarchy'[^4] because there is no known rational standard for them -- thereby making any decision ultimately discretionary.

However, this doesn't mean that we can't consider 'principles [as] norms which require that something be realised to the greatest extent possible given the legal and factual possibilities.'[^5] Inasmuch as the principals we document are connected to what are perceived as universal values, we'll likely have better luck in doing so -- as Bomhoff notes, successful balancing is connected to universal values through _reasonableness_ and _rationality_ where it can be found.

[^1]: Frank M. Coffin, '[Judicial Balancing: The Protean Scales of Justice](https://heinonline.org/HOL/Page?handle=hein.journals/nylr63&div=11&g_sent=1&casa_token=&collection=journals)' (1988) 63 NYU Law Rev 16, 19.
[^2]: Ibid 25.
[^3]: Jacco Bomhoff, '[Balancing, the Global and the Local Judicial Balancing as a Problematic Topic in Comparative (Constitutional) Law](https://repository.uchastings.edu/cgi/viewcontent.cgi?article=1695&context=hastings_international_comparative_law_review)' [2008] 31(2) Hastings Intl & Comp Law Rev 555, 559.
[^4]: Jürgen Habermas, _Between Facts and Norms_ (trans. W. Rehg) (Cambridge 1996), 259.
[^5]: Robert Alexey, _A Theory of Constitutional Rights_ (Oxford 2010), 47-8.

**Comment by lknik** [comment]
Thanks for the legal analysis @mnot. That's indeed more-or-less what I had in mind :)

**Comment by mnot** [comment]
I just skimmed a few papers -- have a lot more reading on the queue :)

**Comment by lknik** [comment]
So I imagine. Either way, I go with anti-trust and competition law now, and there would be plenty of relevant content, too. To simplify let's pick three values: privacy, competition, freedom of speech. First things first, while privacy is being considered in competition proceedings, there is an apparent clash here [1] [2]. But in EU at least (arguably similar in the US, just more costly in proceedings), the balancing is even baked in the primary law in 101(1) vs 101(3) which is already a balance between competition and e.g. innovation. Oh and by the way, it speaks about technology on two sides of the "balance", too (in the "harmful" side, and the "alleviating" side). So, do we really want to enter this territory in a W3C Note? :)

[1] Nottingham, M. (2021). [Playing Fair in the Privacy Sandbox](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3891335): Competition, Privacy and Interoperability Standards. Privacy and Interoperability Standards (February 3, 2021).
[2] [On the governance of privacy-preserving systems](https://lukaszolejnik.com/psgover.pdf) 
[3] Treaty on the Functioning of the European Union, Official Journal 115 , 09/05/2008 P. 0088 - 0089.

**Comment by tobie** [comment]
> I share @lknik's concern here - this isn't algorithmic, someone will need to perform the balancing process, and it's likely to be inherently legalistic. This document is an expression of principles; if legal reasoning is any guide, how to balance them will need to be explored and documented through much discussion and experience, not merely written down ahead of time.

Absolutely. Stating as much, and perhaps clarifying the different processes through which these decisions would be made (TAG review, formal objection process) would be really valuable, imho.

**Comment by lknik** [comment]
> Absolutely. Stating as much, and perhaps clarifying the different processes through which these decisions would be made (TAG review, formal objection process) would be really valuable, imho.

So wait, _balancing_ during the review? And who would be **the arbiter**, because there always must be one? The TAG? Last I checked the desirable experience of the members did not include balancing in a quasi-legal process. I mean, I am not opposing this - someone must ultimately do this, and it may well be the TAG. But let's consider the implications.

**Comment by astearns** [comment]
I personally would not expect balancing or decisions during a TAG review, particularly an early one. At most I might want an evaluation of which principles would likely apply to spark further conversation with people closer to the ideas being reviewed. The TAG might eventually be an arbiter over whether the EWP were adequately considered, but I am guessing that most balancing decisions will be made by people directly involved.

An example: There has been a request to standardize that browsers could ignore locally-installed fonts (reducing fingerprinting, therefore under the “security and privacy are essential” principle). But others have pushed back, noting that some people using minority scripts rely on installed fonts to read their web content (so this runs against the “the web is for all people” principle). The CSS and Internationalization WGs have been debating the balance between these principles for quite a while now in multiple issue threads. We may be close to hammering out a compromise that just needs some implementation experiments to test ideas out. At TAG review, there might not have been enough information available to make a good attempt at balancing in this particular case.

**Comment by tobie** [comment]
Given one of the document's stated purposes is to "inform TAG review of new specifications and candidate additions to published recommendations," clarifying what the TAG is expected to do with those principles sounds valuable, even if, as Alan suggests above, it's only to outline potential conflicts between them and let the WG figure it out.

**Comment by lknik** [comment]
Thanks @tobie for highlighting this. It seems that we may have a problem, then? :-)

**Comment by torgo** [comment]
Hi we've decided to close this one as we think it's out of scope for the document as is. This document isn't meant to be an algorithmic, step-by-step guide for how to apply ethics. It's to highlight and document the ethical issues we've come across. We'd certainly be interested in seeing submissions from the community but we don't think it belongs in this document.
