### ISSUE TITLE
Find a voice

### ISSUE THREAD

**Issue by mnot** [w3ctag/ethical-web-principles#79]
> The web should empower an equitable, informed and interconnected society. It has been, and should continue to be, designed to enable communication and knowledge-sharing for everyone. In order for the web to continue to be beneficial to society, we need to include ethical thinking when we build web technologies, applications, and sites.

These are all just assertions; who is saying it? Why aren't you identifying yourselves? I think this is more powerful / believable: 

> As stewards of the Web's architecture, the TAG believes the the web should empower an equitable, informed and interconnected society. It has been, and should continue to be, designed to enable communication and knowledge-sharing for everyone. In order for the web to continue to be beneficial to society, the W3C community needs to include ethical thinking when we build web technologies, applications, and sites.

If this goes to W3C statement, it can be modified appropriately.

**Comment by torgo** [comment]
Just talking about this in our f2f with @hadleybeeman and @rhiaro. We think we need to not state it as "this is what we, a small group, think" but more of "join our movement" - more manifesto-ish rather than "this is a consensus view of *this* particular group." We also want the Statement process to make it clear that the doc has W3C community support while also not limiting its applicability to that community. We're trying to think of a way to make it more clear who has written and approved this document while also not limiting its scope.

**Comment by cwilso** [comment]
That PR seems somewhat at odds with what you said above:  it says "This is a statement of the ethical principles of the w3c community" while you said it should be more "join our movement than "this is a consensus view of this group [the TAG]".  If you intend this to represent the consensus of the web community, that's great; as per @mnot's comment in the PR, it probably requires a different process to achieve.

**Comment by torgo** [comment]
Hi @cwilso this was added in anticipation that we are moving this through the Statement track - so the point is to make this statement true.

**Comment by cwilso** [comment]
@torgo This is time-relevant to a discussion that we've been having that started here (in #54) and continued in AB-public/issue 53, e.g. https://github.com/w3c/AB-public/issues/53#issuecomment-1427296514.   In particular, I would translate that there appears to be some notion that a Statement track document from an elected body like the TAG or AB might not be "consensus" enough.   (I'd also point out that the TAG seems to make liberal use of closing and locking issues from further discussion, which probably doesn't help defend against that charge.)

I want to be clear that I'm not personally against having this be the statement of the ethical principles of the web community (we build on it in the AB-hosted vision document); just that the way this was written in the PR was not "join our movement", it was "this *is* the community view."

**Comment by darobin** [comment]
I would suggest that it's a question of matching the evidence of wide review to what is being put forward. To give a very rough sense (the examples may not be precise, just attempting to convey the idea):

* A statement of the TAG's opinion on a routine matter of architecture: consensus of TAG members is likely appropriate.
* A statement about a matter pertaining to the W3C (but not broadly to the whole Web), elevated to Statement: evidence of engagement from Members on par with how far-reaching/important/etc. the statement is plus consensus of AC.
* A foundational statement asserting an important aspect pertaining to the whole Web: evidence of engagement from a wide community extending outside of the Consortium, possibly with non-W3C expert input, and ideally with some kind of evidence that we're not fooling ourselves into something (which has happened a few times over our history).

One way to think about it is that a body elected by the W3C Membership cannot alone have greater legitimacy than the W3C Membership itself. I believe that the reason that the Process gives voice to non-Members is precisely because our mission demands that we be more relevant than just to the Membership.

**Comment by torgo** [comment]
@cwilso understood - we can review and make modifications before we update the document in /tr. 

@darobin I agree with your statements but I'm still not sure what the take-away is. Do you think the TAG should be evidencing our engagement with the wider web community when we put this forward for Statement?

**Comment by darobin** [comment]
Well, in the context of this issue I think the most important is to make sure you align the voice and the consensus you have.

"Evidencing" sounds defensive. I assume that the transition to Statement will require evidence of wide review as per usual but I have no idea what the requirements will be. It might be a good idea to enquire early?

More generally, my concern (which I think is what Chris is referring to) is also just to make sure that you don't hit a wall. Today, criteria like a test suite and two implementations are second nature but they had to be argued for against a lot of resistance. They weren't obvious to all. As we have groups producing work that can't be in a browser engine or tested in WPT, I worry about déjà vu. So long as it's advice like "don't do x in APIs, you'll hurt yourself", there's good expert/community cred. But for broader scopes like ethics, the lack of reality check to match what we have elsewhere has some alarm bells blaring for me.

Perhaps a relatable way to think about it is: how do you make sure that you're not producing the XHTML 2 of web governance?

**Comment by torgo** [comment]
We agreed today that we have largely addressed the original issues raised to the degree where we are comfortable moving forward with the Statement process. We appreciate the wider discussion but we feel that's a discussion we should have as part of the wide review.
